import { BasketIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

export const orderTypes = defineType({
  name: "order",
  title: "Order",
  type: "document",
  icon: BasketIcon,
  fields: [
    defineField({
      name: "orderNumber",
      title: "Order Number",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "stripeSessionId",
      title: "Stripe Session ID",
      type: "string",
    }),
    defineField({
      name: "stripeCustomerId",
      title: "Stripe Customer ID",
      type: "string",
    }),
    defineField({
      name: "total",
      title: "Total",
      type: "number",
    }),
    defineField({
      name: "customerName",
      title: "Customer Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "string",
      validation: (Rule) => Rule.required().email(),
    }),
    defineField({
      name: "stripePaymentIntentId",
      title: "Stripe Payment Intent ID",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "products",
      title: "Products",
      type: "array",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "product",
              title: "Product Bought",
              type: "reference",
              to: [{ type: "product" }],
            }),
            defineField({
              name: "quantity",
              title: "Quantity",
              type: "number",
              validation: (Rule) => Rule.min(1).required(),
            }),
          ],
          preview: {
            select: {
              product: "product.name",
              quantity: "quantity",
              price: "product.price",
              image: "product.image",
              currency: "product.currency",
            },
            prepare(select) {
              return {
                title: `${select.product} × ${select.quantity}`,
                subtitle: `${(select.price * (select.quantity || 1)).toFixed(2)} ${select.currency}`,
                media: select.image,
              };
            },
          },
        }),
      ],
    }),
    defineField({
        name: "totalPrice",
        title: "Total Price",
        type: "number",
        validation: (Rule) => Rule.min(0),
    }),
    defineField({
        name: "currency",
        title: "Currency",
        type: "string",
        validation: (Rule) => Rule.required(),
    }),
    defineField({
        name: "amountDiscount",
        title: "Amount Discount",
        type: "number",
        validation: (Rule) => Rule.min(0),
    }),
    defineField({
        name: "status",
        title: "Status",
        type: "string",
        options: {
            list: [
                { title: "Pending", value: "pending" },
                { title: "Paid", value: "paid" },
                { title: "Shipped", value: "shipped" },
                { title: "Delivered", value: "delivered" },
                { title: "Cancelled", value: "cancelled" },
            ],
        },
    }),
    defineField({
        name: "orderDate",
        title: "Order Date",
        type: "datetime",
        validation: (Rule) => Rule.required(),
    }),
    defineField({
        name: "shippingAddress",
        title: "Shipping Address (Bangladesh Only)",
        type: "object",
        fields: [
            defineField({
                name: "fullName",
                title: "Full Name",
                type: "string",
                validation: (Rule) => Rule.required(),
            }),
            defineField({
                name: "phoneNumber",
                title: "Phone Number",
                type: "string",
                validation: (Rule) => Rule.required(),
                description: "Mobile number for delivery contact",
            }),
            defineField({
                name: "district",
                title: "District",
                type: "string",
                options: {
                    list: [
                        { title: "Dhaka", value: "dhaka" },
                        { title: "Chittagong", value: "chittagong" },
                        { title: "Rajshahi", value: "rajshahi" },
                        { title: "Khulna", value: "khulna" },
                        { title: "Barisal", value: "barisal" },
                        { title: "Sylhet", value: "sylhet" },
                        { title: "Rangpur", value: "rangpur" },
                        { title: "Mymensingh", value: "mymensingh" },
                        { title: "Comilla", value: "comilla" },
                        { title: "Narayanganj", value: "narayanganj" },
                        { title: "Gazipur", value: "gazipur" },
                        { title: "Jessore", value: "jessore" },
                        { title: "Bogra", value: "bogra" },
                        { title: "Dinajpur", value: "dinajpur" },
                        { title: "Pabna", value: "pabna" },
                        { title: "Tangail", value: "tangail" },
                        { title: "Jamalpur", value: "jamalpur" },
                        { title: "Kishoreganj", value: "kishoreganj" },
                        { title: "Faridpur", value: "faridpur" },
                        { title: "Manikganj", value: "manikganj" },
                        { title: "Narsingdi", value: "narsingdi" },
                        { title: "Brahmanbaria", value: "brahmanbaria" },
                        { title: "Chandpur", value: "chandpur" },
                        { title: "Lakshmipur", value: "lakshmipur" },
                        { title: "Noakhali", value: "noakhali" },
                        { title: "Feni", value: "feni" },
                        { title: "Cox's Bazar", value: "coxsbazar" },
                        { title: "Bandarban", value: "bandarban" },
                        { title: "Rangamati", value: "rangamati" },
                        { title: "Khagrachhari", value: "khagrachhari" },
                        { title: "Patuakhali", value: "patuakhali" },
                        { title: "Pirojpur", value: "pirojpur" },
                        { title: "Jhalokati", value: "jhalokati" },
                        { title: "Barguna", value: "barguna" },
                        { title: "Bhola", value: "bhola" },
                        { title: "Satkhira", value: "satkhira" },
                        { title: "Bagerhat", value: "bagerhat" },
                        { title: "Narail", value: "narail" },
                        { title: "Chuadanga", value: "chuadanga" },
                        { title: "Kushtia", value: "kushtia" },
                        { title: "Meherpur", value: "meherpur" },
                        { title: "Jhenaidah", value: "jhenaidah" },
                        { title: "Magura", value: "magura" },
                        { title: "Rajbari", value: "rajbari" },
                        { title: "Gopalganj", value: "gopalganj" },
                        { title: "Madaripur", value: "madaripur" },
                        { title: "Shariatpur", value: "shariatpur" },
                        { title: "Sirajganj", value: "sirajganj" },
                        { title: "Natore", value: "natore" },
                        { title: "Naogaon", value: "naogaon" },
                        { title: "Joypurhat", value: "joypurhat" },
                        { title: "Chapainawabganj", value: "chapainawabganj" },
                        { title: "Gaibandha", value: "gaibandha" },
                        { title: "Thakurgaon", value: "thakurgaon" },
                        { title: "Panchagarh", value: "panchagarh" },
                        { title: "Lalmonirhat", value: "lalmonirhat" },
                        { title: "Nilphamari", value: "nilphamari" },
                        { title: "Kurigram", value: "kurigram" },
                        { title: "Netrokona", value: "netrokona" },
                        { title: "Sherpur", value: "sherpur" },
                        { title: "Moulvibazar", value: "moulvibazar" },
                        { title: "Habiganj", value: "habiganj" },
                        { title: "Sunamganj", value: "sunamganj" },
                        { title: "Munshiganj", value: "munshiganj" },
                        { title: "Gopalganj", value: "gopalganj" },
                    ],
                },
                validation: (Rule) => Rule.required(),
            }),
            defineField({
                name: "homeAddress",
                title: "Home Address",
                type: "text",
                validation: (Rule) => Rule.required(),
                description: "Detailed home address within the district (area, road, house number)",
            }),
            defineField({
                name: "country",
                title: "Country",
                type: "string",
                initialValue: "Bangladesh",
                readOnly: true,
            }),
        ],
    }),
    defineField({
        name: "deliveryStatus",
        title: "Delivery Status",
        type: "string",
        options: {
            list: [
                { title: "Order Confirmed", value: "confirmed" },
                { title: "Processing", value: "processing" },
                { title: "Packed", value: "packed" },
                { title: "Shipped", value: "shipped" },
                { title: "Out for Delivery", value: "out_for_delivery" },
                { title: "Delivered", value: "delivered" },
                { title: "Failed Delivery", value: "failed_delivery" },
            ],
        },
        initialValue: "confirmed",
    }),
    defineField({
        name: "deliveryNotes",
        title: "Delivery Notes",
        type: "text",
        description: "Special instructions for delivery",
    }),
  ],
  preview: {
  select: {
    orderNumber: "orderNumber",
    customerName: "customerName",
    totalPrice: "totalPrice",
    currency: "currency",
    email: "email",
  },
  prepare(select) {
    const orderIdSnippet = `${select.orderNumber.slice(0, 5)}...${select.orderNumber.slice(-5)}`;
    return {
      title: `${select.customerName} (${orderIdSnippet})`,
      subtitle: `${select.totalPrice ?? 0} ${select.currency}, ${select.email}`,
      media: BasketIcon,
    };
  },
},
});
